### ISSUE TITLE
FragmentIabHelper does not work with native Fragments prior api 17

### ISSUE THREAD

**Issue by danijoo** [onepf/OPFIab#14]
Hello,

The current version of FragmentIabHelperImpl does not work with native fragments (and PreferenceFragment) prior api level 17. This is because the method getChildFragmentManager() isnt available there. This makes it not possible to use this Helper in PreferenceFragment, which also lacks an official supportversion.
As a workarround I implemented the Activity version and forwarded calls to my settings fragment.

The reason why I opened this issue is because I think this should be pointed out somewhere in the wiki or javadoc. Right now, you have to read the source or find it out the hard way (by exception :p )

Regards,
danijoo

**Comment by RomanZhilich** [comment]
Hi.

I'm pretty sure I mentioned it in the docs. Method `getFragmentHelper(android.app.Fragment)` is also annotated with `@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)` and it's strange if you didn't get warned by your IDE.

But you probably right, I should also mention this on the wiki.

**Comment by RomanZhilich** [comment]
> I'm pretty sure I mentioned it in the docs

```java
/**
...
Nested fragments were introduced in Android API 17, use
{@link #getFragmentHelper(android.support.v4.app.Fragment)} for earlier versions.
...
*/
```

**Comment by danijoo** [comment]
How could I miss this. Sorry :)
