### ISSUE TITLE
Amazon - No Billing Provider

### ISSUE THREAD

**Issue by jakubklos77** [onepf/OPFIab#15]
The library works properly with Google Play but not with the Amazon Store App.
I have downloaded the latest Amazon App and tested with my app and also the Trivial Drive.
These are the logs and results:

```
06-04 13:13:05.774: D/d(2307): In App Purchasing SDK - Sandbox Mode: PurchasingListener registered: org.onepf.opfiab.amazon.AmazonBillingHelper@b3486198
06-04 13:13:05.774: D/d(2307): In App Purchasing SDK - Sandbox Mode: PurchasingListener Context: org.myklos.inote.SettingsView@b33ef490
06-04 13:13:05.814: D/OPF(2307): --> SetupManager.newResponse(org.onepf.opfiab.model.event.SetupStartedEvent@b339aec0);
06-04 13:13:05.814: D/OPF(2307): --> GoogleBillingHelper.isBillingSupported();
06-04 13:13:05.814: D/OPF(2307): Can't bind to service: class com.android.vending.billing.IInAppBillingService$Stub
06-04 13:13:05.844: D/OPF(2307): Check if billing supported: null
06-04 13:13:05.844: D/OPF(2307): Package installer: null
06-04 13:13:06.094: D/OPF(2307): --> BillingEventDispatcher.onSetupResponse({
06-04 13:13:06.094: D/OPF(2307): "authorized": false,
06-04 13:13:06.094: D/OPF(2307): "status": "FAILED",
06-04 13:13:06.094: D/OPF(2307): "provider": null
06-04 13:13:06.094: D/OPF(2307): });

06-04 13:13:55.095: D/org.myklos.inote.LicenseClass(2307): Purchase
06-04 13:13:55.115: D/OPF(2307): --> BillingEventDispatcher.onResponse({
06-04 13:13:55.115: D/OPF(2307): "purchase": null,
06-04 13:13:55.115: D/OPF(2307): "provider_info": null,
06-04 13:13:55.115: D/OPF(2307): "verification_result": null,
06-04 13:13:55.115: D/OPF(2307): "type": "PURCHASE",
06-04 13:13:55.115: D/OPF(2307): "status": "NO_BILLING_PROVIDER"
06-04 13:13:55.115: D/OPF(2307): });
06-04 13:13:55.115: D/org.myklos.inote.LicenseClass(2307): PURCHASE NO_BILLING_PROVIDER
```

It seems the library does not detect the Amazon App installed.

The initialization of the library is as follows:

```java
			// Init configuration
			Configuration configuration = new Configuration.Builder()
		        .addBillingProvider(newGoogleProvider())
		        .addBillingProvider(newAmazonProvider())
		        .setBillingListener(myListener)
		        .build();		
				
			OPFLog.setEnabled(true, true);
			OPFIab.init(mActivity.getApplication(), configuration);
	
		        iabHelper = OPFIab.getAdvancedHelper();
		        iabHelper.register();
	
		        OPFIab.setup();
```
where the newAmazonProvider method is:

```java
    private BillingProvider newAmazonProvider() {
        final MapSkuResolver skuResolver = new MapSkuResolver();
        skuResolver.add(ITEM_SKU, AMAZON_ITEM_SKU);

        return new AmazonBillingProvider.Builder(mContext)
                .setSkuResolver(skuResolver)
                .build();
    }
```    
	
Please, let me know what else you need from me.
Thank you,
Jakub

**Comment by RomanZhilich** [comment]
Some thing you might try to pin point the issue:
* Re-install Amazon store and Amazon App Tester
* Remove Google from config
* Make sure you used correct JSON containing your SKUs with Amazon App Tester
* Uninstall Amazon App Tester and try to installing https://github.com/onepf/OPFIab/tree/master/samples/trivialdrive#amazon from Amazon Store.

**Comment by jakubklos77** [comment]
* I have done this already. Remember that it happens on my Nexus 6 (5.1.1) and also the Android Emulator
* That was the first thing before I submitted this ticket
* I have tried with and without the App Tester. Also I have tried with the Trivial Drive app directly downloaded via the Amazon Store app.

Btw. it must be something with the library because I was able to find the old TrivialDrive app (2 triangles icon - probably the old library version) and it works properly. 

What else can I check?

**Comment by RomanZhilich** [comment]
Hm... I'll try to get my hands on Nexus 6 and reproduce this.

Meanwhile your best option is probably adding Amazon as a module to your project and abuse debugger. If you do, please make sure you used master branch, dev has a lot of unfinished changes and is not suitable for testing.

**Comment by RomanZhilich** [comment]
> I'll try to get my hands on Nexus 6

All could get was a device with newly announced Android M, and Amazon refused to work with it.
Nothing good came out of emulator either. Arm is ridiculously slow, and Amazon app doesn't have x86 support. 

I have a theory why you could have this issue, please check what is the full package name of your Amazon app and post in here.

Also, can you please try [this](https://yadi.sk/d/omX6AsBeh5uZ7] amazon aar, I've added a little bit more logs.

**Comment by jakubklos77** [comment]
Exactly, it has occured to me too. This is what you have in the sources:
    protected static final Collection<String> PACKAGES = Collections.unmodifiableList(
            Arrays.asList("com.amazon.venezia", "com.amazon.mShop.android"));

But when I list the package name using the "pm" command I get
uk.amazon.mShop.android.apk

Could it be it?

**Comment by jakubklos77** [comment]
Amazon does not let me download a non UK version of the app. I have tried and it redirects me. How many country versions are there? The questions are

1. Will it work with any other than those 2 in the PACKAGES collection?
2. If yes shouldn't you maybe use regex in the collection?

Thank you

**Comment by jakubklos77** [comment]
I have tried the amazon aar and just confirms what we both tought. It does not detect the package because it checks for different names:

06-05 08:31:53.381: D/dalvikvm(2514): GC_FOR_ALLOC freed 524K, 12% free 5036K/5700K, paused 9ms, total 15ms
06-05 08:31:53.411: D/d(2514): In App Purchasing SDK - Sandbox Mode: PurchasingListener registered: org.onepf.opfiab.amazon.AmazonBillingHelper@b33eaa80
06-05 08:31:53.421: D/d(2514): In App Purchasing SDK - Sandbox Mode: PurchasingListener Context: org.myklos.inote.SettingsView@b348d190
06-05 08:31:53.431: D/OPF(2514): --> SetupManager.newResponse(org.onepf.opfiab.model.event.SetupStartedEvent@b3452128);
06-05 08:31:53.431: D/OPF(2514): --> GoogleBillingHelper.isBillingSupported();
06-05 08:31:53.431: D/OPF(2514): Can't bind to service: class com.android.vending.billing.IInAppBillingService$Stub
06-05 08:31:53.431: D/OPF(2514): Check if billing supported: null
06-05 08:31:53.431: D/OPF(2514): --> AmazonBillingProvider.isAvailable();
06-05 08:31:53.431: D/OPF(2514): Amazon package not found!
06-05 08:31:53.431: D/OPF(2514): Package installer: null
06-05 08:31:53.511: W/EGL_emulation(2514): eglSurfaceAttrib not implemented
06-05 08:31:53.611: D/OPF(2514): --> BillingEventDispatcher.onSetupResponse({
06-05 08:31:53.611: D/OPF(2514):     "authorized": false,
06-05 08:31:53.611: D/OPF(2514):     "status": "FAILED",
06-05 08:31:53.611: D/OPF(2514):     "provider": null
06-05 08:31:53.611: D/OPF(2514): });

**Comment by RomanZhilich** [comment]
> Could it be it? 

It's definitely it.

Thank you very much for your report, I'll see what I can do. 
> If yes shouldn't you maybe use regex in the collection?

This is most likely the best solution.

**Comment by RomanZhilich** [comment]
I've gone with [regex](https://github.com/onepf/OPFIab/blob/d530630e886af99353fb231f81f7ea50fbb6cd78/opfiab-providers/amazon/src/main/java/org/onepf/opfiab/amazon/AmazonBillingProvider.java#L78) hopefully it'll do for now.

**Comment by jakubklos77** [comment]
Thank you very much. I have tested by changing the package collection myself yesterday and it worked fine.
