### ISSUE TITLE
Remove dependency on EventBus

### ISSUE THREAD

**Issue by cachapa** [onepf/OPFIab#28]
I'm not sure if this is the right forum for discussing this, but I would like to propose completely removing the dependency on EventBus.

While EB is a nice library for some use cases, I disagree with the forced dependency for the following reasons:
- The project might already be using another bus library (e.g. Otto)
- Architecture policy might disallow event busses altogether
- The functionality afforded by EventBus can be completely replaced with a standard Observable / Listener pattern
- Projects which use EventBus might have problems if their EB version differs from OPFIab's
- It's generally preferable for libraries to include as few dependencies as possible - follow the Unix principle of doing one thing and doing it well

**Comment by RomanZhilich** [comment]
Hello.

I understand your concerns, but this was an architectural decision in early stages of development an I don't think it's going anywhere any time soon. Too much things are tied to it:
* Components communication
* Concurrency
* Extensibility

Lets look at your arguments:
> The project might already be using another bus library (e.g. Otto)

They don't conflict in any way and you should not have any problems.
> Architecture policy might disallow event busses altogether

I'm not sure about this, but library doesn't force you to use EventBus. You can use listeners to communicate with and EventBus will only be used internally.
> The functionality afforded by EventBus can be completely replaced with a standard Observable / Listener pattern

Sure, everything can be replaced. But it's not as nearly easy as it sounds. As I mention all concurrency code relies on EventBus.
> Projects which use EventBus might have problems if their EB version differs from OPFIab's

Well this might be a problem. If you encounter something like this create a new issue and we'll try to figure out a workaround.
> It's generally preferable for libraries to include as few dependencies as possible - follow the Unix principle of doing one thing and doing it well

I'm aware of that, but one always has to make choices. I decided to include EventBus and this resulted in much cleaner architecture and cleaner code (at least to my taste).

So... sorry but EventBus stays for now.

**Comment by cachapa** [comment]
Thanks for the detailed response.

I generally disagree with the notion that it makes no difference to include an extra dependency if it's not used. Setting aside the issues of app size and method count limits, the reality is that every code line in the app is a potential source of bugs and security issues.

Perhaps it makes more sense to explain why I'm not a big fan of event bus libraries in general:
- They flatten OO hierarchy - you might as well have all of your classes in the same package
- They make debugging much harder since it's difficult to associate events with actions
- There's no way to restrict events to a section of the app - events which should be private to OPFIab can be sent or handled from any class in the app

Essentially, EBs are a convenient way to avoid dealing with the constructs which invented exactly to force us into good software architectures.

This is why I'm worried about including this dependency in the library which is going to handle purchasing in our app. Security is important and code cleanliness is paramount to achieving that security.

I do agree that removing the library at this point might be difficult, but I think it's a worthwhile endeavour.
Generally it should be possible to simply replace the EB register/unregister hooks with subscribe/unsubscribe calls. Where this isn't possible, would be in places where your architecture is violating the OO hierarchy principle, and an excellent opportunity for refactoring those problem areas.

The other pain point would be concurrency handling. I do understand that EB has a very convenient method of handling threading, but it should be possible to achieve the same results without having to carry the baggage EB brings with it.

Anyway, thanks for listening. I hope you don't take this as a criticism of your code, but rather as an attempt for constructive discussion on development fundamentals.

**Comment by RomanZhilich** [comment]
Hi.
>Setting aside the issues of app size and method count limits

Library itself if only 44KB and I'm pretty sure it doesn't contribute much to method count.
> reality is that every code line in the app is a potential source of bugs and security issues.

That was actually one of the reasons I turned to EventBus in the first place. I'm quite satisfied with their code quality and it's proven to be reliable by many users. Also I think my concurrent code would have contained more bugs had I written it all by myself.

> They flatten OO hierarchy - you might as well have all of your classes in the same package

Actually many libraries do exactly that: [Picasso](https://github.com/square/picasso/tree/master/picasso/src/main/java/com/squareup/picasso) [Android-Checkout](https://github.com/serso/android-checkout/tree/master/lib/src/main/java/org/solovyev/android/checkout). But I dislike this approach. One way or another different components has to communicate, EB just makes this communication a bit more unrestricted and it seems fine to me.

> They make debugging much harder since it's difficult to associate events with actions 

This is true to some degree, but it still manageable once you get a hold of it. Modern IDE offer handy find usage actions so it's not such a big problem.

> There's no way to restrict events to a section of the app - events which should be private to OPFIab can be sent or handled from any class in the app

Actually EvenBus object is only accessible from OPFIab class so not just anyone can subscribe to receive events. Sure you can access it with reflection, but you can just as well do it without EventBus.

> This is why I'm worried about including this dependency in the library which is going to handle purchasing in our app. Security is important and code cleanliness is paramount to achieving that security.

I don't see the point here. I'm not quite convinced that EventBus makes library less secure. And code definitely would be less clean without EB.

> I do agree that removing the library at this point might be difficult, but I think it's a worthwhile endeavour.

Sorry, I still disagree. You are welcome to do it in your fork though, that what Open Source is all about.

> Generally it should be possible to simply replace the EB register/unregister hooks with subscribe/unsubscribe calls.

So... you offer to implement same EventBus pattern but within the library so it wouldn't have third party dependencies? Why not just copy\paste EB implementation?

> Anyway, thanks for listening. I hope you don't take this as a criticism of your code, but rather as an attempt for constructive discussion on development fundamentals.

Your arguments is fine. Sorry if I sound a little bit harsh. The thing is I already had this discussion during library development and I'm still sure that all in all EB has more pros then cons.

**Comment by cachapa** [comment]
>> They flatten OO hierarchy - you might as well have all of your classes in the same package

> Actually many libraries do exactly that: Picasso Android-Checkout. But I dislike this approach. One way or another different components has to communicate, EB just makes this communication a bit more unrestricted and it seems fine to me.

I was actually presenting that as something that I thought we would both agree is bad practice. I had no idea anyone would actually use it in production code. To be fair, Picasso at least (I'm not familiar with Android Checkout) is more of a composition of other libraries which actually do most of the work, so I guess that's more excusable in their case (even it's still disappointing to see it).

> This is true to some degree, but it still manageable once you get a hold of it. Modern IDE offer handy find usage actions so it's not such a big problem.

The problem isn't just during coding, but rather during debugging. When you're debugging it's hard to know where a given event was generated if you have more than one source. For one, it renders the call stack essentially useless.

> Actually EvenBus object is only accessible from OPFIab class so not just anyone can subscribe to receive events. Sure you can access it with reflection, but you can just as well do it without EventBus.

This may be something you can claim now that the project is still small and you're the only contributor, but you can't guarantee that this will be true in future versions.

> So... you offer to implement same EventBus pattern but within the library so it wouldn't have third party dependencies? Why not just copy\paste EB implementation?

You deleted the most important part of my message. By replacing EB with a listener pattern, you will be forced to deal with places where your observers and observables aren't directly accessible to each other in the object hierarchy. Any place where you're using EB to drill through your hierarchy is a code smell - or in this case, an architecture smell.

By using EB you're trading architectural cleanliness for convenience, and this will inevitably end up coming back to you. I know this because I have been down the exact same road in the past and have paid the price.

I fear that by insisting on using EB as a central point of your architecture you're hurting the adoption of your library as well as contributions from other developers.

Having said that, it's your project and it's become pretty clear to me that you're not willing to entertain the idea of removing EB, so there's not really much point to continue this discussion.
