### ISSUE TITLE
Mandatory orderId field for Google provider

### ISSUE THREAD

**Issue by OSemenovBoyarka** [onepf/OPFIab#37]
There is a check in dev library version, that requires purchase json to have orderId field, if library is not in debug mode. 
https://github.com/onepf/OPFIab/blob/dev/opfiab-providers/google/src/main/java/org/onepf/opfiab/google/GoogleBillingProvider.java#L164

However, in-app purchases can be tested from PlayStore Beta distribution channel, which will contain app in release build type, obviously. And google sends empty orderId for test purhases. 

In that manner, test purchase can never complete in app, downloaded from Beta channel.

I think this check should be removed from library and how about you, devs?

**Comment by RomanZhilich** [comment]
Debug attribute in library doesn't necessarily mean Debug build type (although it's most logical case). You can supply this value yourself. And it stands to reason that it should be true for beta builds.

**Comment by OSemenovBoyarka** [comment]
Thanks for quick response. Yeap, I've ended up set debug attribute to true for all my builds. 
So real issue here is lack of documentation, as I can see now.

**Comment by OSemenovBoyarka** [comment]
It was already discussed in #32, sorry, haven't found that PR. I'll close the issue then
